controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    leg_position_controller:
      type: forward_command_controller/ForwardCommandController

leg_position_controller:
  ros__parameters:
    joints:
      - rr_hip
      - lr_hip
      - rf_hip
      - lf_hip
      - rr_thigh_joint
      - rf_thigh_joint
      - lr_thigh_joint
      - lf_thigh_joint
      - rr_foot_joint
      - rf_foot_joint
      - lr_foot_joint
      - lf_foot_joint
    interface_name: position
