#!/usr/bin/env python3
"""M6.0-A OFFLINE trajectory conversion and preflight
(see spiderx_controller/m6_offline_preflight.py).

    ros2 run spiderx_controller m6_offline_preflight [--check-only] [--trajectory FILE] [--out DIR]
"""
import sys

from spiderx_controller.m6_offline_preflight import main

if __name__ == '__main__':
    sys.exit(main())
