#!/usr/bin/env python3
"""Check the spiderx_controller configs, the M1 <ros2_control> integration and the M2
simulation-only posture config against the SpiderX URDF. Exit code 0 = pass."""
import argparse
import sys

from spiderx_controller.config_check import (
    check, check_m2_posture, check_ros2_control, load_configs, load_control_urdf,
    load_passive_fortress_urdf, load_urdf)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--urdf', help='URDF file (default: expand the installed SpiderX xacro)')
    parser.add_argument('--config-dir', help='config directory (default: installed share)')
    args = parser.parse_args()
    configs = load_configs(args.config_dir)
    errors, info = check(load_urdf(args.urdf), *configs)
    if not args.urdf:
        e2, i2 = check_ros2_control(load_control_urdf(), configs[0], load_passive_fortress_urdf())
        errors += e2
        info += i2
    e3, i3 = check_m2_posture(configs[0], args.config_dir)
    errors += e3
    info += i3
    for line in info:
        print(f'[OK]   {line}')
    for line in errors:
        print(f'[FAIL] {line}')
    print('Controller configuration: ' + ('FAILED' if errors else 'valid'))
    return 1 if errors else 0


if __name__ == '__main__':
    sys.exit(main())
